### ISSUE TITLE
Como Consultar Domínios do Serviço de Nomes da Solana (.sol)

### ISSUE THREAD

**Issue by guilhermeboaventurarodrigues** [w3b3d3v/content-videos-PT#35]
🌐 Embarque em uma jornada de descoberta com nosso vídeo exclusivo: "Como Consultar Domínios do Serviço de Nomes da Solana (.sol)". Explore as nuances do ecossistema Solana e mergulhe na arte de consultar e compreender os domínios no serviço de nomes, abrindo portas para novas possibilidades na blockchain.

💡 Ao longo deste guia detalhado, desvendaremos os passos essenciais para consultar domínios no serviço de nomes da Solana (.sol). Descubra como essa funcionalidade se torna crucial no contexto da Solana e como pode impactar positivamente o seu envolvimento com essa vibrante blockchain.

🔴 Inscreva-se agora no Discord e junte-se a comunidade web3dev que forma desenvolvedores para o mercado da Web3.
Participe da construção e compartilhe suas opiniões com gente. Não perca a oportunidade de estar no centro da revolução tecnológica!

👉 Acesse o link para conectar agora: https://discord.web3dev.com.br/youtube

#solana #servicodenomes #blockchain #sol #consultadedominios #guia #discord #comunidadesolana

**Comment by JoaoPFS0** [comment]
https://youtu.be/KIXZLPbhwcc
