### ISSUE TITLE
Onboarding no Midiático

### ISSUE THREAD

**Issue by annabida** [w3b3d3v/content-videos-PT#42]
# 🚀 Onboarding no Squad Midiático 🎬

- Entender como funciona os times no canal [`#🔭・how-to-join`](https://discord.com/channels/898706705779687435/1110017328009187358).
- Verificar se esta com a role `@Interested in the teams`.
- Participar das [weeklies no discord](https://discord.com/events/898706705779687435/1232412015667187803) do time

---

# 🗳️ Sistema de Propostas de Vídeo

> ⚠️ **Verifique os critérios de aprovação**
> 
> **Para que uma proposta seja aprovada, é necessário que 10 ou mais membros da comunidade a considerem relevante**.
> Você pode mostrar sua aprovação **reagindo com 👍**, indicando que a proposta é **digna do esforço de gravação**.
> [🔗 Contribua também avaliando as propostas de outros membros sempre que desejar em nosso Discord](https://discord.com/channels/898706705779687435/1169368391723778048).

## Para avançar com a sua proposta, siga os seguintes passos abaixo:
Uma vez aprovada conforme o processo de votação, a proposta estará pronta para avançar no processo de criação e publicação neste quadro.

### 1. Título do tema proposto.
Adicione o título do tema proposta para o vídeo no campo principal do card.

### 2. Descreva detalhadamente a ideia proposta, incluindo as expectativas para o conteúdo:
Na parte de "write" forneça um resumo da ideia, destacando palavras-chave importantes, o que ajudará na estratégia de SEO. Este texto também pode ser utilizado na criação da legenda do vídeo. 

### 3. Informações adicionais importantes:
- Sugestões de hashtags.
- Se deseja ser responsável pela gravação da proposta, caso ela seja aprovada.
- Tags identificando o tamanho do vídeo.
- Links relevantes relacionados ao tema.
- Referências ou outros elementos relevantes.

### 4. Converta o card "draft" em uma issue dentro do repositório "squad-midiatico-videos-PT" e preencha todos os campos do menu à direita deste card:
- **Assignees**: membros envolvidos na produção, indicando os responsáveis.
- **Criador de Vídeo**: identifique quem será responsável pela gravação do vídeo proposto. Se for você, preencha seu nome no campo.
- **Copywriter**: identifique quem será responsável pela descrição do vídeo nas redes sociais, criando uma legenda para a publicação e otimizando o texto conforme as boas práticas de SEO. Se for você, preencha seu nome no campo.
- **Editor de Vídeo**: identifique quem fará a edição e pós-produção do vídeo. Se for você, preencha seu nome no campo.
- **Social Media**: identifique quem será responsável pela publicação, agendamento, upload e acompanhamento do desempenho da publicação. Se for você, preencha seu nome no campo.

> 👀 **Observação**: Se o seu nome não estiver listado, entre em contato com um dos líderes do Midiático para realizar o seu Onboarding.

**Comment by allluz** [comment]
# Processo de votação das propostas de vídeos no Discord

Atenção antes de criar um card (issue) verifique abaixo o seguinte critério de aprovação 👇
> Para a proposta ser aprovada 10 membros da comunidade precisam reagir com 👍  sinalizando que o tema é relevante e vale o trabalho de gravação.
> [Contribua também avaliando as propostas de outros membros sempre que quiser no nosso discord](https://discord.com/channels/898706705779687435/1169368391723778048)

# Para avançar com a sua proposta siga os seguintes passos abaixo:
A proposta após aprovada conforme o processo de votação, está pronta para seguir o processo de criação e publicação nesse quadro, para isso crie uma issue nesse projeto - modelo kanban - preenchendo as seguintes informações.

## 1- Título do tema proposto para o vídeo no campo principal da postagem

## 2- Na parte "write" aqui, coloque a descrição da ideia proposta detalhando o que se espera do conteúdo:
Coloque um resumo da ideia escolhendo palavra chaves importantes - isso ajudará para a estratégia de SEO. 
Inclusive esse texto pode ser aproveitado para criação da legenda que estará no vídeo - trabalho do membro copywriter.

## 3- Acrescente informações importantes adicionais, por exemplo:
- sugestões de hastags;
- informe se deseja ser responsável pela gravação da proposta caso ela seja aprovada;
- coloque as tags na publicação identificando o tamanho do vídeo;
- adicione links importantes relacionados com o tema;
- referências ou/e outros.

## 4- Converta o card ''draft'' em uma issue dentro do repository "squad-midiatico-videos-PT" do github da w3b3d3v e preencha todos o campos do menu a direita desse card (issue), principalmente.
- assignees = membros envolvidos na produção, assinalando os membros responsáveis.
- Criador de vídeo = identifique quem é responsável pela gravação do vídeo proposto - se você for o responsável, preencha seu nome no campo.
- Copywriter = identifique quem é responsável pela descrição do vídeo nas redes sociais, criando uma legenda da publicação e otimizando o texto conforme as boas práticas de SEO - se você for o responsável, preencha seu nome no campo.
- Editor de vídeo = identifique quem é fará a edição e pós-produção do vídeo - se você for o responsável, preencha seu nome no campo.
- Social media = identifique quem é responsável pela publicação, agendamento, upload e acompanhamento do desempenho da publicação - se você for o responsável, preencha seu nome no campo.

Obs: Se o seu nome não está listado, procure um dos líderes do Midiático para realizar o seu Onboarding.

**Comment by allluz** [comment]
# Como criar uma issue nesse board

Atenção antes de criar um card (issue) verifique abaixo o seguinte critério de aprovação 👇
> Para a proposta ser aprovada 10 membros da comunidade precisam reagir com 👍  sinalizando que o tema é relevante e vale o trabalho de gravação.
> [Contribua também avaliando as propostas de outros membros sempre que quiser no nosso discord](https://discord.com/channels/898706705779687435/1169368391723778048)

# Para avançar com a sua proposta siga os seguintes passos abaixo:
A proposta após aprovada conforme o processo de votação, está pronta para seguir o processo de criação e publicação nesse quadro, para isso crie uma issue nesse projeto - modelo kanban - preenchendo as seguintes informações.

## 1- Título do tema proposto para o vídeo no campo principal da postagem

## 2- Na parte "write" aqui, coloque a descrição da ideia proposta detalhando o que se espera do conteúdo:
Coloque um resumo da ideia escolhendo palavra chaves importantes - isso ajudará para a estratégia de SEO. 
Inclusive esse texto pode ser aproveitado para criação da legenda que estará no vídeo - trabalho do membro copywriter.

## 3- Acrescente informações importantes adicionais, por exemplo:
- sugestões de hastags;
- informe se deseja ser responsável pela gravação da proposta caso ela seja aprovada;
- coloque as tags na publicação identificando o tamanho do vídeo;
- adicione links importantes relacionados com o tema;
- referências ou/e outros.

## 4- Converta o card ''draft'' em uma issue dentro do repository "squad-midiatico-videos-PT" do github da w3b3d3v e preencha todos o campos do menu a direita desse card (issue), principalmente.
- assignees = membros envolvidos na produção, assinalando os membros responsáveis.
- Criador de vídeo = identifique quem é responsável pela gravação do vídeo proposto - se você for o responsável, preencha seu nome no campo.
- Copywriter = identifique quem é responsável pela descrição do vídeo nas redes sociais, criando uma legenda da publicação e otimizando o texto conforme as boas práticas de SEO - se você for o responsável, preencha seu nome no campo.
- Editor de vídeo = identifique quem é fará a edição e pós-produção do vídeo - se você for o responsável, preencha seu nome no campo.
- Social media = identifique quem é responsável pela publicação, agendamento, upload e acompanhamento do desempenho da publicação - se você for o responsável, preencha seu nome no campo.

Obs: Se o seu nome não está listado, procure um dos líderes do Midiático para realizar o seu Onboarding.
