### ISSUE TITLE
Como Escrever e Implantar um Contrato Inteligente em Rust

### ISSUE THREAD

**Issue by JABAGAMEHUNTER** [w3b3d3v/content-videos-PT#46]
Com a inicial popularidade da linguagem de programação, pode ser interessante a adoção da mesma no mundo web3
Artigo de referência:
https://pt.w3d.community/paulogio/como-escrever-e-implantar-um-contrato-inteligente-em-rust-454

**Comment by JABAGAMEHUNTER** [comment]
Video enviado para o drive:
https://drive.google.com/file/d/14yOHuVc-DKJff2i2Imbrc4JgMQ3yHQ_z/view?usp=sharing

**Comment by JABAGAMEHUNTER** [comment]
Video enviado para o google drive: https://drive.google.com/file/d/1Gt1v0nnnEgJDttyFdJ-UmPcNhbKcXN42/view?usp=sharing

**Comment by JABAGAMEHUNTER** [comment]
codigo fonte do projeto: https://github.com/near-examples/crossword-tutorial-chapter-1

**Comment by JoaoPFS0** [comment]
https://youtu.be/Q7yyYbJygkM
