### ISSUE TITLE
Como escrever contratos NEP-171 NFT em Rust

### ISSUE THREAD

**Issue by JABAGAMEHUNTER** [w3b3d3v/content-videos-PT#47]
## Roteiro:
Introdução / Conteúdo / Comente #tag se assistiu até o final / Chamada para os grupos

## Título do vídeo:
Como escrever contratos NEP-171 NFT em Rust

## Título da Thumbnail:
Como escrever contratos NEP-171 NFT em Rust

## Link da Thumbnail:
**@JoaoPFS0** upload

## Descrição do vídeo:

Neste tutorial, criaremos uma arte NFT colecionável simples chamada Flarn, que consiste em um nome, uma descrição e uma imagem JPEG. Nosso contrato inteligente permitirá que os Flarns sejam criados, coletados e negociados na blockchain NEAR.
Artigo de referência: https://pt.w3d.community/diogoj/escrever-contratos-nep-171-nft-em-rust-2pj6

💻 Quer aprender Rust, a linguagem de programação moderna e poderosa usada para desenvolvimento de sistemas seguros e de alto desempenho?
🔗 Junte-se ao nosso grupo de estudos de Rust! https://l.w3d.community/grupos

📚 Um espaço dedicado para explorar os conceitos, técnicas e melhores práticas da programação em Rust. Ideal para desenvolvedores que buscam aprimorar suas habilidades e criar software robusto, eficiente e seguro.

🌐 Participe da WEB3DEV no Discord: Não perca a oportunidade de fazer parte da comunidade de desenvolvedores Rust! Compartilhe suas opiniões, aprenda e colabore com outros entusiastas.
👉 Acesse nosso Discord agora: https://l.w3d.community/discord

## Hashtags (Descrição):

#Rust #Programação #DesenvolvimentoDeSoftware #SistemasSeguros #web3 #tecnologia #desenvolvedores #performance #coding #comunidade #educação

## Tags (Tema):

Rust, Programação, Desenvolvimento de Software

**Comment by JABAGAMEHUNTER** [comment]
Link do projeto no comentário fixado:
https://github.com/near-examples/nft-tutorial/tree/main/nft-contract-basic

**Comment by JABAGAMEHUNTER** [comment]
Video enviado para o drive: https://drive.google.com/file/d/1Z2Q3NFAjctRIRKLzxS-Mc15BDyvtHnJY/view?usp=sharing

**Comment by JoaoPFS0** [comment]
https://youtu.be/twEN1-nQWNY
