### ISSUE TITLE
Como começar com Truffle? Seja um Desenvolvedor FullStack em Web3!

### ISSUE THREAD

**Issue by JABAGAMEHUNTER** [w3b3d3v/content-videos-PT#5]
INFORMAÇÕES SOBRE O VÍDEO:

Membro responsável pela criação:Judá Matheo

Título da Thumbnail:Truffle?! FullStack en Web3!

Sugestões de hastags:#Web3 #Solidity #Blockchain #InícioDeCarreira #Ethereum

DESCRIÇÃO DA PROPOSTA DO VÍDEO:Neste vídeo, será demonstrado passo a passo como iniciar o desenvolvimento de projetos Web3 usando a suite de desenvolvimento Truffle, voltada para a blockchain Ethereum.Será utilizado um idioma de programação chamado Solidity para realizar essa criação.Esse vídeo é relevante, pois serve para introduzir desenvolvedores novos ao cenário de desenvolvimento web3 usando uma suite completa e descomplicada.No vídeo, será explicado como o desenvolvedor pode passar de um simples "dev" para um "builder" adotando a suite de desenvolvimento Truffle, atingindo quem quer começar web3 sem se complicar.Informações adicionais:
hastags:
links úteis: https://trufflesuite.com/guides/ultimate-guide-to-truffle-the-gateway-to-full-stack-blockchain-development/

**Comment by JABAGAMEHUNTER** [comment]
Vídeo adicionado ao drive da web3dev
[https://drive.google.com/file/d/1Gw9J9nbA0xgK_57mbocWbeb58qX3w1iq/view?usp=drive_link](url)

**Comment by JABAGAMEHUNTER** [comment]
Apenas falta a intro de chamada do vídeo

**Comment by JABAGAMEHUNTER** [comment]
Adicionado vídeo de intro
[https://drive.google.com/file/d/1resHGYxNZudCzRg9LrQl4EZxa8v2Ct6C/view?usp=drive_link](url)

**Comment by JoaoPFS0** [comment]
https://youtu.be/aGGyHoNKkRE
