### ISSUE TITLE
Contrato Inteligente Pausável em Solidity

### ISSUE THREAD

**Issue by guilhermeboaventurarodrigues** [w3b3d3v/content-videos-PT#50]
https://drive.google.com/drive/folders/1yl_Y8YzwwokdK49xaw1hLazsR4i9r1Ew?hl=pt-br

**Comment by JoaoPFS0** [comment]
https://youtu.be/ZhVYQcuBFH8

**Comment by JoaoPFS0** [comment]
https://youtu.be/KBNBZoXReTk
