### ISSUE TITLE
 rust-state-machine #5 - Criando funções para gerenciar contas no pallet

### ISSUE THREAD

**Issue by allluz** [w3b3d3v/content-videos-PT#59]
https://drive.google.com/file/d/1ZEBLfAZUiRDZK78nh5DS7zB4Otyae54g/view?usp=drivesdk

**Comment by allluz** [comment]
Junte-se ao nosso grupo de estudos de Rust e domine uma das linguagens de programação mais seguras e rápidas do mercado. Aprenda a desenvolver software de alto desempenho com Rust, desde sistemas operacionais até aplicações Web e blockchain. Este grupo é perfeito para programadores que buscam aumentar sua eficiência e segurança no código, aproveitando as características únicas que Rust oferece. 

Clique e participe em nosso Discord { https://l.w3d.community/grupos

**Comment by JoaoPFS0** [comment]
https://youtu.be/coBI_avKIMw
