### ISSUE TITLE
Chamada para o fórum 360º News

### ISSUE THREAD

**Issue by annabida** [w3b3d3v/content-videos-PT#6]
@guilhermeboaventurarodrigues conforme mencionamos em reunião da Squad segue o roteiro do shorts abaixo sobre o assunto do fórum de notícias, para fazermos uma versão mais longa.
Apresente ao roteiro os seguintes tópicos:
* Configuração do canal "Conferir Canais" para garantir o acesso.
* Apresentar a localização do fórum no servidor
* Citar notícias publicadas anteriormente brevemente, duas ou três
* Mostrar como realizar uma publicação (verificar com o @allluz alguma notícia que selecionamos previamente)
* Convidar os membros a realizarem o compartilhamento de notícias que consomem em outras plataformas
* Enfatizar a importância de comentar e contribuir com a verificação de fontes, para termos a validação da vericidade e confiabilidade da notícia.
* Mencionar que as melhores notícias serão publicadas na nossa newsletter

**Comment by annabida** [comment]
@guilhermeboaventurarodrigues segue o roteiro:

Falaaa Builders Estou com o Discord da nossa WEB3DEV aberto para uma novidade bacana, rápida e relevante do nosso servidor.  Criamos o fórum 360 news para quem busca sempre se manter atualizado e deseja acessar notícias com boa triagem de âmbito mais técnico sobre tecnologias Blockchain e do mercado Web3. Vem comigo que vou te mostrar onde fica: Você encontra o fórum no menu lateral esquerdo, depois das categorias, Onboarding, WEB3DEV e Encontros, ao localizar a seção da Comunidade, facilmente pode acessar o 360 news. Além de ser um espaço de informação, você pode participar dos debates de forma ativa e contribuir com publicação de notícias que te impactaram. Assim fazemos uma curadoria coletiva de conteúdo, de forma aberta, para compor a nossa newsletter. Então o recado esse, um convite para que entre no servidor do Discord, encontre o fórum e aproveite o espaço 360 news para sanar toda e qualquer desinformação. Espero te encontrar por lá!

Segue a gravação do vídeo shorts: https://drive.google.com/drive/u/0/folders/1GOipG0AA04Or6b56fpzYCvtTz6UCx934

**Comment by guilhermeboaventurarodrigues** [comment]
https://drive.google.com/drive/folders/1S1tr-CbPFHgWA2tLzw0bW2HslKOjdfK9?hl=pt-br

**Comment by JoaoPFS0** [comment]
https://youtu.be/6PfqT48Aang
