### ISSUE TITLE
Grupo de Estudos de Solidity #2

### ISSUE THREAD

**Issue by allluz** [w3b3d3v/content-videos-PT#65]
https://drive.google.com/drive/folders/1zcEzvNYFsE5dGgohvDjcwXFTYupUsybJ

**Comment by allluz** [comment]
Descubra como a economia dos tokens molda o universo das criptomoedas. Nosso grupo de estudos de Token Economics oferece um mergulho nas estratégias de design e impacto econômico dos tokens no mercado. Indicado para investidores, empreendedores e curiosos sobre a dinâmica financeira da blockchain.

Clique e participe https://l.w3d.community/grupos

**Comment by viniblack** [comment]
@allluz por que esse card foi para blocked?

**Comment by viniblack** [comment]
Qualidade de audio ruim
