### ISSUE TITLE
Fundamentos de uma DAO

### ISSUE THREAD

**Issue by JABAGAMEHUNTER** [w3b3d3v/content-videos-PT#81]
## Roteiro:
Introdução / Conteúdo / Comente #tag se assistiu até o final / Chamada para os grupos

## Título do vídeo: 
Fundamentos de uma DAO

## Título da Thumbnail: 
**@JoaoPFS0** upload
Fundamentos de uma DAO

## Descrição do vídeo:

💻 Quer entender e dominar o funcionamento das Organizações Autônomas Descentralizadas (DAOs)?
🔗 Junte-se ao nosso grupo de estudos de DAOs! https://l.w3d.community/grupos

📚 Um espaço dedicado para aprender sobre a estrutura, governança e operação das DAOs. Ideal para entusiastas de blockchain, desenvolvedores e qualquer pessoa interessada em explorar novas formas de organização e tomada de decisão descentralizadas.

🌐 Participe da WEB3DEV no Discord: Não perca a oportunidade de fazer parte da revolução organizacional! Compartilhe suas opiniões, aprenda e ajude a moldar o futuro das organizações.
👉 Acesse nosso Discord agora: https://l.w3d.community/discord

## Tags (Tema): 

DAOs, Organizações Autônomas Descentralizadas, Governança Descentralizada

**Comment by JABAGAMEHUNTER** [comment]
Adicionado video na pasta do drive
https://drive.google.com/file/d/1znrTWbR_pg6seT_iVKbBQZekhknemOcu/view?usp=drive_link

**Comment by viniblack** [comment]
@JABAGAMEHUNTER consegue add os links aqui dos sites que você mostrou no video?

**Comment by JABAGAMEHUNTER** [comment]
The State of DAO Tooling: https://medium.com/1kxnetwork/organization-legos-the-state-of-dao-tooling-866b6879e93e
MetacartelVentures: https://www.metacartel.org/
Projeto aprovado na Polkadot: https://polkadot.polkassembly.io/referenda/627 
Grupo de estudos WEB3DEV: https://pt.w3d.community/blog/grupos-de-estudos-2024-df8

**Comment by JoaoPFS0** [comment]
https://youtu.be/YPONZwPmBaY
