### ISSUE TITLE
Google I/O Edit

### ISSUE THREAD

**Issue by allluz** [w3b3d3v/content-videos-PT#88]
## Roteiro:
Material de suporte / Daniel Cukier

## Descrição do vídeo:
🚀 Nosso fundador, Daniel Cukier, marcou presença no Google I/O! Ele participou de palestras incríveis sobre as últimas tendências em tecnologia e discutiu o futuro da Web3. Fique ligado para mais novidades e insights que ele trará diretamente de um dos maiores eventos de inovação do mundo!

**Comment by allluz** [comment]
https://drive.google.com/drive/folders/15fxiFty1Pqm9xNgNlm4gmC_oI_ohSH7b

**Comment by allluz** [comment]
🚀 Nosso fundador, Daniel Cukier, marcou presença no Google I/O! Ele participou de palestras incríveis sobre as últimas tendências em tecnologia e discutiu o futuro da Web3. Fique ligado para mais novidades e insights que ele trará diretamente de um dos maiores eventos de inovação do mundo!

**Comment by JoaoPFS0** [comment]
https://youtu.be/9W3Ud8V9-Ng
