### ISSUE TITLE
O que é o Solana Saga? Um smarthphone web 3.0

### ISSUE THREAD

**Issue by guilhermeboaventurarodrigues** [w3b3d3v/content-videos-PT#9]
O Solana Saga é o primeiro smartphone do mundo focado em Web3. Ele é baseado no sistema operacional Android, mas vem com uma série de recursos extras que o tornam ideal para o uso de criptomoedas e aplicativos blockchain.

Entre esses recursos, estão:

Um seed vault integrado, que armazena as palavras-chave de recuperação da carteira de criptomoedas do usuário de forma segura;

Suporte nativo a NFTs, permitindo que os usuários armazenem, visualizem e transacionem NFTs diretamente no telefone;

Um Dapp Store dedicado, que fornece acesso a uma variedade de aplicativos Web3.

🔴 Inscreva-se agora no Discord e junte-se a comunidade web3dev que forma desenvolvedores para o mercado da Web3.
Participe da construção e compartilhe suas opiniões com gente. Não perca a oportunidade de estar no centro da revolução tecnológica!

👉 Acesse o link para conectar agora: https://discord.web3dev.com.br/youtube

#SolanaSaga #web3 #smartphone #criptomoedas #blockchain #futurodacripto #tecnologia #investimentos #nft #android #smartphoneandroid #inovaçãotecnológica #galaxynft #web3gaming #metaverso #criptomoedasbr #tecnobr #web3br

**Comment by JoaoPFS0** [comment]
a

**Comment by JoaoPFS0** [comment]
https://youtu.be/a_AMILkscek
